export const schema = [
    `CREATE TABLE IF NOT EXISTS schema_migrations (
        version INTEGER PRIMARY KEY,
        applied_at INTEGER NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS contacts (
        id INTEGER PRIMARY KEY,
        display_name TEXT,
        push_name TEXT,
        username TEXT,
        phone_number TEXT,
        country_code TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS contact_identities (
        id INTEGER PRIMARY KEY,
        contact_id INTEGER NOT NULL,
        identifier_type TEXT NOT NULL,
        value TEXT NOT NULL UNIQUE,
        is_primary INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
        UNIQUE (contact_id, identifier_type, value)
    )`,
    `CREATE TABLE IF NOT EXISTS chats (
        id INTEGER PRIMARY KEY,
        jid TEXT NOT NULL UNIQUE,
        chat_type TEXT NOT NULL CHECK (chat_type IN ('direct', 'group', 'broadcast', 'newsletter', 'status', 'other')),
        name TEXT,
        contact_id INTEGER,
        unread_count INTEGER,
        archived INTEGER CHECK (archived IS NULL OR archived IN (0, 1)),
        pinned INTEGER,
        mute_end_ms INTEGER,
        marked_as_unread INTEGER CHECK (marked_as_unread IS NULL OR marked_as_unread IN (0, 1)),
        ephemeral_expiration INTEGER,
        ephemeral_setting_timestamp INTEGER,
        last_message_at INTEGER,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS groups (
        id INTEGER PRIMARY KEY,
        chat_id INTEGER NOT NULL UNIQUE,
        owner_contact_id INTEGER,
        subject TEXT,
        subject_owner_contact_id INTEGER,
        description TEXT,
        description_id TEXT,
        size INTEGER,
        created_at_ms INTEGER,
        subject_updated_at_ms INTEGER,
        description_updated_at_ms INTEGER,
        addressing_mode TEXT,
        ephemeral_duration INTEGER,
        ephemeral_trigger INTEGER,
        restrict_enabled INTEGER,
        announce_enabled INTEGER,
        is_parent_group INTEGER,
        is_closed_community INTEGER,
        default_subgroup INTEGER,
        general_subgroup INTEGER,
        hidden_subgroup INTEGER,
        allow_non_admin_subgroup_creation INTEGER,
        limit_sharing_enabled INTEGER,
        membership_approval_enabled INTEGER,
        member_add_mode TEXT,
        member_link_mode TEXT,
        member_share_group_history_mode TEXT,
        participant_label_enabled INTEGER,
        evolution_version INTEGER,
        growth_locked_expiration INTEGER,
        appeal_status TEXT,
        appeal_update_time INTEGER,
        linked_parent_group_chat_id INTEGER,
        no_frequently_forwarded_enabled INTEGER,
        support_enabled INTEGER,
        suspended INTEGER,
        incognito INTEGER,
        allow_admin_reports INTEGER,
        auto_add_disabled INTEGER,
        group_history_enabled INTEGER,
        capi_enabled INTEGER,
        group_safety_check INTEGER,
        is_deleted INTEGER NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1)),
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
        FOREIGN KEY (owner_contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
        FOREIGN KEY (subject_owner_contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
        FOREIGN KEY (linked_parent_group_chat_id) REFERENCES chats(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS group_members (
        id INTEGER PRIMARY KEY,
        group_id INTEGER NOT NULL,
        contact_id INTEGER,
        jid TEXT NOT NULL,
        lid_jid TEXT,
        phone_jid TEXT,
        display_name TEXT,
        username TEXT,
        role TEXT,
        is_admin INTEGER NOT NULL DEFAULT 0 CHECK (is_admin IN (0, 1)),
        is_super_admin INTEGER NOT NULL DEFAULT 0 CHECK (is_super_admin IN (0, 1)),
        expiration_seconds INTEGER,
        active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
        joined_at INTEGER,
        left_at INTEGER,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
        FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
        UNIQUE (group_id, jid)
    )`,
    `CREATE TABLE IF NOT EXISTS messages (
        id INTEGER PRIMARY KEY,
        chat_id INTEGER NOT NULL,
        message_id TEXT NOT NULL,
        from_me INTEGER NOT NULL CHECK (from_me IN (0, 1)),
        sender_contact_id INTEGER,
        sender_jid TEXT,
        sender_alt_jid TEXT,
        participant_jid TEXT,
        participant_alt_jid TEXT,
        recipient_jid TEXT,
        recipient_alt_jid TEXT,
        sender_username TEXT,
        recipient_username TEXT,
        sender_device INTEGER,
        server_id INTEGER,
        push_name TEXT,
        timestamp_ms INTEGER,
        stanza_type TEXT,
        message_type TEXT,
        offline INTEGER,
        expiration_seconds INTEGER,
        delivery_status TEXT,
        raw_message BLOB,
        raw_event_json TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
        FOREIGN KEY (sender_contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
        UNIQUE (chat_id, message_id, from_me)
    )`,
    `CREATE TABLE IF NOT EXISTS message_quotes (
        message_id INTEGER PRIMARY KEY,
        quoted_message_row_id INTEGER,
        quoted_message_id TEXT NOT NULL,
        quoted_chat_jid TEXT,
        quoted_participant_jid TEXT,
        quoted_from_me INTEGER,
        quoted_message BLOB,
        created_at INTEGER NOT NULL,
        FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
        FOREIGN KEY (quoted_message_row_id) REFERENCES messages(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS message_receipts (
        id INTEGER PRIMARY KEY,
        message_row_id INTEGER,
        message_id TEXT NOT NULL,
        chat_jid TEXT,
        status TEXT NOT NULL,
        from_self_device INTEGER NOT NULL CHECK (from_self_device IN (0, 1)),
        participant_jid TEXT,
        participant_username TEXT,
        recipient_jid TEXT,
        occurred_at INTEGER NOT NULL,
        raw_event_json TEXT,
        FOREIGN KEY (message_row_id) REFERENCES messages(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS message_events (
        id INTEGER PRIMARY KEY,
        message_row_id INTEGER,
        event_type TEXT NOT NULL,
        message_id TEXT,
        chat_jid TEXT,
        occurred_at INTEGER NOT NULL,
        payload_json TEXT,
        raw_payload BLOB,
        FOREIGN KEY (message_row_id) REFERENCES messages(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS group_events (
        id INTEGER PRIMARY KEY,
        group_id INTEGER,
        action TEXT NOT NULL,
        author_contact_id INTEGER,
        group_jid TEXT,
        context_group_jid TEXT,
        timestamp_ms INTEGER,
        subject TEXT,
        subject_owner_jid TEXT,
        description TEXT,
        description_id TEXT,
        code TEXT,
        expiration_seconds INTEGER,
        mode TEXT,
        enabled INTEGER,
        reason TEXT,
        request_method TEXT,
        details_json TEXT,
        raw_event_json TEXT,
        created_at INTEGER NOT NULL,
        FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL,
        FOREIGN KEY (author_contact_id) REFERENCES contacts(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS group_event_participants (
        id INTEGER PRIMARY KEY,
        group_event_id INTEGER NOT NULL,
        contact_id INTEGER,
        jid TEXT,
        lid_jid TEXT,
        phone_jid TEXT,
        display_name TEXT,
        username TEXT,
        role TEXT,
        expiration_seconds INTEGER,
        FOREIGN KEY (group_event_id) REFERENCES group_events(id) ON DELETE CASCADE,
        FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS group_event_links (
        id INTEGER PRIMARY KEY,
        group_event_id INTEGER NOT NULL,
        jid TEXT,
        subject TEXT,
        subject_timestamp_ms INTEGER,
        hidden_subgroup INTEGER,
        FOREIGN KEY (group_event_id) REFERENCES group_events(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS group_event_membership_requests (
        id INTEGER PRIMARY KEY,
        group_event_id INTEGER NOT NULL,
        contact_id INTEGER,
        jid TEXT,
        username TEXT,
        phone_jid TEXT,
        FOREIGN KEY (group_event_id) REFERENCES group_events(id) ON DELETE CASCADE,
        FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS group_event_subgroup_suggestions (
        id INTEGER PRIMARY KEY,
        group_event_id INTEGER NOT NULL,
        group_jid TEXT,
        owner_jid TEXT,
        subject TEXT,
        description TEXT,
        timestamp_ms INTEGER,
        is_existing_group INTEGER,
        participant_count INTEGER,
        reason TEXT,
        FOREIGN KEY (group_event_id) REFERENCES group_events(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS history_sync_chunks (
        id INTEGER PRIMARY KEY,
        sync_type INTEGER NOT NULL,
        messages_count INTEGER NOT NULL,
        conversations_count INTEGER NOT NULL,
        pushnames_count INTEGER NOT NULL,
        inline_contacts_count INTEGER NOT NULL,
        chunk_order INTEGER,
        progress INTEGER,
        occurred_at INTEGER NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS group_history_bundles (
        id INTEGER PRIMARY KEY,
        group_chat_id INTEGER,
        group_jid TEXT NOT NULL,
        sender_contact_id INTEGER,
        bundle_message_id TEXT,
        messages_count INTEGER NOT NULL,
        out_of_window_pins_count INTEGER NOT NULL,
        dropped_count INTEGER NOT NULL,
        oldest_timestamp_ms INTEGER,
        history_receivers_json TEXT,
        occurred_at INTEGER NOT NULL,
        FOREIGN KEY (group_chat_id) REFERENCES chats(id) ON DELETE SET NULL,
        FOREIGN KEY (sender_contact_id) REFERENCES contacts(id) ON DELETE SET NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_contact_identities_contact ON contact_identities(contact_id)`,
    `CREATE INDEX IF NOT EXISTS idx_contacts_phone_number ON contacts(phone_number)`,
    `CREATE INDEX IF NOT EXISTS idx_contacts_username ON contacts(username)`,
    `CREATE INDEX IF NOT EXISTS idx_chats_type ON chats(chat_type)`,
    `CREATE INDEX IF NOT EXISTS idx_chats_last_message_at ON chats(last_message_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_group_members_group_active ON group_members(group_id, active)`,
    `CREATE INDEX IF NOT EXISTS idx_group_members_contact ON group_members(contact_id)`,
    `CREATE INDEX IF NOT EXISTS idx_messages_chat_timestamp ON messages(chat_id, timestamp_ms DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_messages_sender_timestamp ON messages(sender_contact_id, timestamp_ms DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_messages_message_id ON messages(message_id)`,
    `CREATE INDEX IF NOT EXISTS idx_message_receipts_message ON message_receipts(message_id)`,
    `CREATE INDEX IF NOT EXISTS idx_message_events_message ON message_events(message_id)`,
    `CREATE INDEX IF NOT EXISTS idx_message_events_chat_time ON message_events(chat_jid, occurred_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_group_events_group_time ON group_events(group_id, timestamp_ms DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_group_event_participants_event ON group_event_participants(group_event_id)`,
    `CREATE INDEX IF NOT EXISTS idx_group_history_bundles_group_time ON group_history_bundles(group_jid, occurred_at DESC)`
];

export const schemaVersion = 2;
